### ISSUE TITLE
Test TP1 - assertion error

### ISSUE THREAD

**Issue by uncyzer** [frederic-mallet/cop-l3-miage#2]
Pour le TP1 : `TortueTest.java`

La méthode `assertEquals(double d1, double d2)` est dépreciée selon [assertEquals](https://junit.org/junit4/javadoc/4.8/org/junit/Assert.html#assertEquals(double,%20double)).

L'utilisation de `assertEquals(double d1, double d2, double delta)` devrait être utilisé pour retirer les codes warning et anticiper l'utilisation de version JUnit 5

**Comment by frederic-mallet** [comment]
Non ce n'est pas un bug. Dans l'énoncé on vous dit que la direction est un angle (un entier).
Vous avez le problème de dépreciation car vous devez utiliser un double à la place.
Il faut stocker un double pour la précision (en radian) mais il faut renvoyer un int. La tortue a des visées pédagogiques. 92.8degré ça ne parle pas beaucoup à l'utilisateur "moyen".
